### ISSUE TITLE
Add REST API for web app?

### ISSUE THREAD

**Issue by cmdcolin** [primer3-org/primer3plus#1]
Hi there,
I was wondering if it would be possible to add a REST API for the primer3 web app or if that has been thought of before. It would be really useful! 

Thanks

**Comment by cmdcolin** [comment]
Also, if CORS (cross-origin resource access) would be allowed that would be very ideal

**Comment by untergasser** [comment]
Please run Primer3 on your own server if you need it.

Best,

Andreas
