### ISSUE TITLE
Results are different from https://www.bioinformatics.nl

### ISSUE THREAD

**Issue by FredericBGA** [primer3-org/primer3plus#16]
Hello,

I've installed a Primer3plus website from this git repository.
But when, for example, I run the "Check Primer" task the results (and the interface also) are quite different.

Sequence: aatcatcatacgac
```
Using www.bioinformatics.nl
Length: | 14 bp
Tm: | 32.0 °C
GC: | 35.7 %
ANY: | 4.0
SELF: | 2.0
3' Stability: | 7.8 ΔG
```

```
Using my web site
Length: | 14 bp
Tm: | 37.8 C
GC: | 35.7 %
Any Dimer: | 0.0
End Dimer: | 0.0
Template Mispriming: | 3.0
Hairpin: | 0.0
3' Stability: | 4.3 ΔG
Penalty: | 28.204
```
I can see that on the sourceforge web site (https://sourceforge.net/p/primer3/primer3plus/ci/master/tree/) there are some commit (related to  Bugs Found by Heidelberg Bioinformatics Course) that are not present here in this git repository.

It is possible to merge those versions? Do I need to submit a PR?
How can I get the same results as www.bioinformatics.nl web site?
thank you.

**Comment by FredericBGA** [comment]
Hi,

ok, I've found how to get the same results, I need to load the right settings `p3 V1.1.4 def`

So what about the small bugs that are only fixed on sourceforge?

**Comment by FredericBGA** [comment]
Hello

I've use "Primer_Check" with this primer `TTCTCCTTTGGGCCGTG` on https://www.bioinformatics.nl/cgi-bin/primer3plus/primer3plus.cgi. 

- There is a warning regarding `Left primer is unacceptable: High 3' stability` 
- And nothing about the length, even if in "General Settings" the min length is set to `18`

Using my web site and this git repo, with the same primer.

- No warning regarding the stability.
- A warning complaining about the size `Error: Specified right primer < PRIMER_MIN_SIZE` as in "General Settings" the min length is set to `18`

Do I miss the stability warning? And why there is no issue detected around the primer length on https://www.bioinformatics.nl/cgi-bin/primer3plus/primer3plus.cgi? Which site is the best?

Thank you.

Fred

**Comment by untergasser** [comment]
Hi,

so let me explain. www.bioinformatics.nl was the first Primer3Plus release we prepared. It is not under my control and I think it is now 10 years behind and therefore I can not see into the settings or comment on the parameters. The latest version is on dev.primer3plus.com. I will within a few month also update primer3plus.com, which is a 3 year old version, to the same version as dev.primer3plus.com. A one year old version is available on https://www.gear-genomics.com/primer3plus/

In future, https://www.gear-genomics.com/primer3plus/ and www.primer3plus.com and dev.primer3plus.com will have the same version now available at dev.primer3plus.com.

If I continue some developments, will move on dev.primer3plus.com to try things out. This server is cutting edge. Once it is stable and I like my changes, I will sync https://www.gear-genomics.com/primer3plus/ and www.primer3plus.com to this version.

I hope that helps.

The sourceforge additions are in the github repo, just way back. With the release tomorrow, I will sync them to the same level.

Best,

Andreas

**Comment by FredericBGA** [comment]
Yes! Perfect.
Thank you Andreas.

Fred
