### ISSUE TITLE
Ability to pass parameters through URL

### ISSUE THREAD

**Issue by BeatWolf** [primer3-org/primer3plus#19]
Hi,

previous versions of primer3 allowed to pass parameters to the web interface through the URL, like this:

https://www.primer3plus.com/index.html?SEQUENCE_TEMPLATE=TCCGGCTCTGCTCCTGGCTGGGGGTCTCCTTGGCCTTCTTACAGGTGTACAGCCACTTGATGATGCGGGCGTTCCTCTCGATGACCGAAGTGGTGCTGGGCACCTGCTCTATCAGCTCCTCCTCCTGCAGCCCCTCGTCGTCGCCGCCGC%5BTGTGCCGGGAGAAGCCGCTGCCGGAGGTGGCGACGCTCACGCTGCGCACCTTGAGGGTCACACAGTCCGACCCCGCGGTGAAGTTCTCCCTCCCCAGGGCCTCCACCACCTCGGGGTCCAGGCCGCAGTACTGGAAGAAGGTGTCAGACTCGGCCAAGGCAGCGGAATAGCGGGAGCTGAGGTCCGACTGTGAGCGCTGCA%5DGCCCCCGACGCCTCACCACCCGCGGCTCTGGCCCAGGGGGCGCGGCCGGGACACTGGAGGGCGCCGCGGACCGCGCGGCTGGGGCTGGGGTCTCGGGGATTGCGGGGTCCGCCGCGGGGCCAGGAGTGGTCGGGACCGTCTCCGGGTTC

This was very useful to integrate primer3 into other tools so that the user does not have to copy the sequence manually.

Is there a reason this functionality was removed and could it maybe come back?

thanks for your help and your great work.

**Comment by untergasser** [comment]
Hi,

the javascript heavy version made things more complicated, but it is still there. You need now to use the upload address:
https://www.primer3plus.com/primer3plus/api/v1/upload?SEQUENCE_TEMPLATE=TCCGGCTCTGCTCCTGGCTGGGGGTCTCCTTGGCCTTCTTACAGGTGTACAGCCACTTGATGATGCGGGCGTTCCTCTCGATGACCGAAGTGGTGCTGGGCACCTGCTCTATCAGCTCCTCCTCCTGCAGCCCCTCGTCGTCGCCGCCGC%5BTGTGCCGGGAGAAGCCGCTGCCGGAGGTGGCGACGCTCACGCTGCGCACCTTGAGGGTCACACAGTCCGACCCCGCGGTGAAGTTCTCCCTCCCCAGGGCCTCCACCACCTCGGGGTCCAGGCCGCAGTACTGGAAGAAGGTGTCAGACTCGGCCAAGGCAGCGGAATAGCGGGAGCTGAGGTCCGACTGTGAGCGCTGCA%5DGCCCCCGACGCCTCACCACCCGCGGCTCTGGCCCAGGGGGCGCGGCCGGGACACTGGAGGGCGCCGCGGACCGCGCGGCTGGGGCTGGGGTCTCGGGGATTGCGGGGTCCGCCGCGGGGCCAGGAGTGGTCGGGACCGTCTCCGGGTTC

I hope this works for you.

Best,

Andreas

**Comment by untergasser** [comment]
I forgot to mention: GET and POST requests work with this address (in case the sequence is long)...

**Comment by BeatWolf** [comment]
Thank you, that is perfect!
