### ISSUE TITLE
setting file primer3plus_2_4_2_default_settings.txt

### ISSUE THREAD

**Issue by ptranvan** [primer3-org/primer3plus#2]
Hi,

I have use the setting file 

primer3plus_2_4_2_default_settings.txt

with primer3core (command line version) and I don't have the same result than the web version (http://www.bioinformatics.nl/cgi-bin/primer3plus/primer3plus.cgi). 

have you done some modifications ?

Thanks.

**Comment by untergasser** [comment]
Hi,

have a look at primer3plus.com, our up to date version. The version at bioinformatics.nl is not maintained by us and might be not up to date.

primer-blast settings might be available from the NCBI.

Best,

Andreas

**Comment by ptranvan** [comment]
Thanks @untergasser. Indeed, I was looking at the wrong website.
