### ISSUE TITLE
Hybridization oligo penalty weight

### ISSUE THREAD

**Issue by schmart95** [primer3-org/primer3plus#23]
Hi there,

I am using Primer3Plus version 3.3.0 and I am frequently running into problems when trying to design primer pairs with internal hybridization oligos.
To me it seems impossible to set a Hyb Oligo Penalty Weight other than 0. If I do set the penalty to e.g. 1, the task runs forever and doesn't finish.
Also the "pick primer list" task doesn't seem to work for me when trying to select an internal oligo alongside primers.
If I remember correctly, these things used to work fine 1-2 years ago before primer3plus was updated.
Is this a known issue?
Am I missing something?

Best, Martin

**Comment by untergasser** [comment]
It worked for me. But I fixed several things, can you try at:
https://dev.primer3plus.com/

Best,
Andreas
