### ISSUE TITLE
No response from the server trying to load default settings from server.

### ISSUE THREAD

**Issue by admi2u** [primer3-org/primer3plus#4]
Hi,
I installed prime3 and prime3plus according to the steps and started it. When accessing the web page, I was prompted  `No response from the server trying to load default settings from server.` I do not know what caused this.
![no-reponse](https://user-images.githubusercontent.com/36391186/69620146-d80b6700-1077-11ea-9235-99cd1fb46aa8.png)
![console-error](https://user-images.githubusercontent.com/36391186/69620160-db065780-1077-11ea-9321-c9da49d6bf27.png)

Can you give me some suggestions?

**Comment by untergasser** [comment]
The server has an error. You need to follow the steps in the readme or inspect the various log files.

Best,

Andreas
