### ISSUE TITLE
Exon-exon span junction assay in primer3plus

### ISSUE THREAD

**Issue by AmirFartash** [primer3-org/primer3plus#8]
I want to design primer pairs while spanning an exon-exon junction through primer3plus. 
when I determine my exon boundary as a target and also highlight some nucleotide of adjacent exons as an included region(around 5 nucleotides from each adjacent exon) it expresses "Too many included regions" and when I just determine my exon boundary as a target it dies not give me any primer pairs. Surprisingly, when I do the design with the NCBI, I have a bunch of primer pair suggestions. can anyone help me how to overcome this problem in primer3plus?
thank you in advanced

**Comment by untergasser** [comment]
Exon-Exon boundaries should be marked with Primer overlap positions. There can only be one included region, it is not useful here.

Best,

Andreas
